### ISSUE TITLE
Executing a .me() produces an authentication error, even after fully authenticated.

### ISSUE THREAD

**Issue by CodeBeater** [bitcapital-hq/bitcapital-core-sdk#23]
Trying to run a .me() (as the example below), even after authenticated, makes the SDK throw an error
```typescript
  @Get('/test')
  public static async test(request: BaseRequest, response: BaseResponse) {

    const me = await BitCapitalService.bitCapitalClient.users().me();
    response.success(me);

  }
```

Which produces the following stacktrace:
```json
{
    "status": 500,
    "message": "[500] Invalid value \"undefined\" for header \"Authorization\" (stackId: 2c790e00-9919-45eb-9d72-7945cbf0c4c8)",
    "stackId": "2c790e00-9919-45eb-9d72-7945cbf0c4c8",
    "details": {
        "code": "ERR_HTTP_INVALID_HEADER_VALUE"
    },
    "stack": "TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value \"undefined\" for header \"Authorization\"\n    at Object.<anonymous> (C:/Users/Raphael/AppData/Local/Yarn/Data/global/node_modules/agent-base/patch-core.js:23:20)\n    at Object.request (C:/Users/Raphael/Desktop/Exchange/node_modules/agent-base/patch-core.js:23:20)\n    at RedirectableRequest._performRequest (C:/Users/Raphael/Desktop/Exchange/node_modules/follow-redirects/index.js:186:24)\n    at new RedirectableRequest (C:/Users/Raphael/Desktop/Exchange/node_modules/follow-redirects/index.js:69:8)\n    at Object.wrappedProtocol.request (C:/Users/Raphael/Desktop/Exchange/node_modules/follow-redirects/index.js:363:14)\n    at dispatchHttpRequest (C:/Users/Raphael/Desktop/Exchange/node_modules/axios/lib/adapters/http.js:132:25)\n    at new Promise (<anonymous>)\n    at httpAdapter (C:/Users/Raphael/Desktop/Exchange/node_modules/axios/lib/adapters/http.js:18:10)\n    at dispatchRequest (C:/Users/Raphael/Desktop/Exchange/node_modules/axios/lib/core/dispatchRequest.js:59:10)"
}
```

**Comment by CodeBeater** [comment]
Screenshot for better context
![image](https://user-images.githubusercontent.com/7710219/51682896-ab0da400-1fcf-11e9-95f4-175fb964b21b.png)

**Comment by luiseduardobrito** [comment]
I suspect this is happening only for client_credentials authenticated users. We'll investigate further.
